In [70]:
#import necessary assets

import warnings
warnings.simplefilter("ignore") 

import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

from sklearn.metrics import r2_score

In [71]:
#read the data from the dataset
cars = pd.read_csv("car_dataset.csv")

In [72]:
#visualize the data
cars.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [73]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

In [74]:
# Use the .isnull() method to locate missing data
missing_values = cars.isnull()
missing_values

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,False,False,False,False,False,False,False,False,False
8124,False,False,False,False,False,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,False,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,False,False,False,False
8127,False,False,False,False,False,False,False,False,False,False,False,False,False

In [75]:
#drop duplicates

In [76]:
#drop unnecessary variables
cars = cars[["selling_price", "km_driven", "mileage", "seats"]].dropna()

#drop rows with missing values
cars.dropna(inplace=True)

cars.head()

   selling_price  km_driven     mileage  seats
0         450000     145500   23.4 kmpl    5.0
1         370000     120000  21.14 kmpl    5.0
2         158000     140000   17.7 kmpl    5.0
3         225000     127000   23.0 kmpl    5.0
4         130000     120000   16.1 kmpl    5.0

In [77]:
#convert mileage to numerical date by taking only the digits
cars['mileage'] = cars['mileage'].str.extract(r'(\d+\.?\d*)').astype(float)

#i used google gemini to learn how to extract the numerical values

In [78]:
#use scaler

In [79]:
# Split data into 'X' features and 'y' target label sets
X = cars[['km_driven', 'mileage', 'seats']]

#the target is y because we want to predict how much a car will cost
y = cars['selling_price']

In [80]:
# Split data set into training and test sets
#use a 70% training/30% testing split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

In [81]:
#create and train model: Elastic Net Regression
#(selected becuase Elastic Net is good for predicting prices based on inputs)

# Initialize a model
ENModel = ElasticNet(alpha=1.0, l1_ratio=0.5)

#fit the model
ENModel.fit(X_train, y_train)

ElasticNet()

In [82]:
#do a little test

# Predict the price of a car with 150000 miles, 23.5 kmpl, and 5 seats
prediction = ENModel.predict([[150000, 23.5, 5.0]])
print("Predicted price is", np.round(prediction, 2))

#looks right to me

Predicted price is [270642.61]

In [83]:
#evaluate the model using r-squared
r2 = ENModel.score(X_test, y_test)

print(r2)

#i used google gemini to learn how to use the r-squared function

0.0948842041284309

In [84]:
#the model only predicted correctly 9% of the time
#however, my prediction based on sample values returned a believable car price

#important predictors: mileage, kmpl, seats